<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHnrBRz5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHnrBRz5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHnrBRz5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHnrBRz5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHnrBRz5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HnrBRz5',
    'container.build_id' => '077fe4a7',
    'container.build_time' => 1631621968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHnrBRz5');
